name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行同步（可以根据需要调整时间）
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork
      uses: actions/checkout@v2
      with:
        ref: main  # 或者替换为你的目标分支（如V2）

    - name: Set Up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/nikkinikki-org/OpenWrt-nikki.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Merge Upstream into Fork
      run: |
        git checkout main  # 或者替换为你的目标分支（如V2）
        git merge upstream/main  --allow-unrelated-histories  # 强制合并不同历史的分支
        git push origin main  # 或者替换为你的目标分支
